#!/usr/bin/env python

from os import linesep
from os.path import join, dirname
from setuptools import setup, find_packages
from subprocess import check_output

# http://blogs.nopcode.org/brainstorm/2013/05/20/pragmatic-python-versioning-via-setuptools-and-git-tags/
# Fetch version from git tags, and write to version.py.
# Also, when git is not available (PyPi package), use stored version.py.
version_py = join(dirname(__file__), join('yadda', 'version.py'))

try:
    short_cmd = 'git describe --always --tags --match v*'.split(' ')
    short_version = check_output(short_cmd).decode().rstrip()[1:]
    full_cmd  = short_cmd + ['--long', '--dirty=+']
    full_version = check_output(full_cmd).decode().rstrip()[1:]
except:
    execfile(version_py)
    short_version = short
    full_version = full

with open(version_py, 'w') as fh:
    fh.write("""# Do not edit; generated by setup.py and git
short='%s'
full='%s'
""" % (short_version, full_version))

setup(
    name = "yadda",
    version = short_version,
    packages = find_packages(),
    test_suite = 'tests',
    entry_points = {
        'console_scripts': [
            'yadda = yadda.main:main',
            ],
        },
)
